"use client";

import { useState, useEffect } from "react";
import { 
  FileText, Download, ShieldCheck, History, User, Loader2, 
  CheckCircle2, AlertTriangle, FileBarChart, Search, Filter, Calendar
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { API_BASE_URL } from "@/lib/config"; // <--- IMPORT THIS

// --- TYPES ---
interface Loan {
  id: number;
  borrower_name: string;
  risk_status: string;
}

interface Alert {
  id: number;
  message: string;
  type: "critical" | "warning";
  timestamp: string;
}

export default function ReportsPage() {
  const [loans, setLoans] = useState<Loan[]>([]);
  const [auditLogs, setAuditLogs] = useState<Alert[]>([]);
  const [loading, setLoading] = useState(true);
  
  // Generation State
  const [selectedLoanId, setSelectedLoanId] = useState<string>("");
  const [reportType, setReportType] = useState<"compliance" | "audit">("compliance");
  const [generating, setGenerating] = useState(false);

  // 1. FETCH REAL DATA
  useEffect(() => {
    const fetchData = async () => {
      try {
        const loansRes = await fetch(`${API_BASE_URL}/api/loans`);
        const loansData = await loansRes.json();
        setLoans(loansData);

        const alertsRes = await fetch(`${API_BASE_URL}/api/alerts`);
        const alertsData = await alertsRes.json();
        setAuditLogs(alertsData);
      } catch (error) {
        console.error("Failed to load report data", error);
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, []);

  // 2. SIMULATE REPORT GENERATION
  const handleGenerateReport = () => {
    if (!selectedLoanId) {
      alert("Please select a borrower first.");
      return;
    }

    setGenerating(true);
    const loan = loans.find(l => l.id.toString() === selectedLoanId);
    
    setTimeout(() => {
      const element = document.createElement("a");
      const fileContent = `
===================================================================
                     COMPLIANCE CERTIFICATE
===================================================================
INSTITUTION:    Covenant IQ Financial Services
BORROWER:       ${loan?.borrower_name}
DATE:           ${new Date().toLocaleDateString()}
REPORT ID:      ${Math.floor(Math.random() * 1000000)}
STATUS:         ${loan?.risk_status.toUpperCase()}

-------------------------------------------------------------------
1. FINANCIAL COVENANTS SUMMARY
   - Debt to EBITDA:      [CALCULATED] - SEE ATTACHMENT A
   - Interest Coverage:   [CALCULATED] - SEE ATTACHMENT A
   
2. CERTIFICATION
   We hereby certify that the above information is true and correct 
   derived from the unaudited financial statements.

3. DEFAULT STATUS
   ${loan?.risk_status === 'Healthy' ? 'No Default has occurred and is continuing.' : 'NOTICE: A Potential Event of Default has been detected.'}

-------------------------------------------------------------------
GENERATED BY COVENANT IQ SYSTEM | ${new Date().toISOString()}
SECURE HASH: ${Math.random().toString(36).substring(2, 15)}
===================================================================
      `;
      
      const file = new Blob([fileContent], {type: 'text/plain'});
      element.href = URL.createObjectURL(file);
      element.download = `${reportType === 'compliance' ? 'Compliance_Cert' : 'Audit_Log'}_${loan?.borrower_name.replace(/\s/g, '_')}.txt`;
      document.body.appendChild(element); 
      element.click();
      document.body.removeChild(element);
      
      setGenerating(false);
    }, 1500); 
  };

  return (
    <div className="space-y-8 max-w-7xl mx-auto pb-20">
      
      {/* PAGE HEADER */}
      <div className="flex justify-between items-end border-b border-zinc-200 pb-6">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-zinc-900">Regulatory Reporting</h1>
          <p className="text-zinc-500 mt-1">Generate standardized compliance documents and review system activity.</p>
        </div>
        <div className="flex gap-2">
           <Button variant="outline" size="sm" className="h-9">
             <History className="h-4 w-4 mr-2" /> Archived Reports
           </Button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* LEFT COLUMN: REPORT GENERATOR WIZARD */}
        <div className="lg:col-span-1 space-y-6">
          <Card className="bg-zinc-900 text-white border-zinc-800 shadow-2xl relative overflow-hidden">
            {/* Decorative background blur */}
            <div className="absolute top-0 right-0 w-64 h-64 bg-red-600/10 rounded-full blur-3xl -mr-16 -mt-16 pointer-events-none"></div>
            
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <FileText className="h-5 w-5 text-red-500" /> Report Wizard
              </CardTitle>
              <CardDescription className="text-zinc-400">
                Generate official LMA-standard documentation.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-5 relative z-10">
              
              <div className="space-y-2">
                <label className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest">1. Select Entity</label>
                <Select onValueChange={setSelectedLoanId}>
                  <SelectTrigger className="w-full bg-zinc-800 border-zinc-700 text-white focus:ring-red-600 h-10">
                    <SelectValue placeholder={loading ? "Loading..." : "Select Borrower..."} />
                  </SelectTrigger>
                  <SelectContent className="bg-zinc-800 border-zinc-700 text-white">
                    {loans.map((loan) => (
                      <SelectItem key={loan.id} value={loan.id.toString()}>
                        {loan.borrower_name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-2">
                 <label className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest">2. Report Type</label>
                 <div className="grid grid-cols-2 gap-3">
                    <div 
                      onClick={() => setReportType("compliance")}
                      className={`p-3 rounded-lg border cursor-pointer transition-all ${
                        reportType === "compliance" 
                          ? "border-red-500 bg-red-500/10" 
                          : "border-zinc-700 bg-zinc-800/50 hover:bg-zinc-800"
                      }`}
                    >
                        <div className="flex items-center gap-2 mb-1">
                           <FileBarChart className={`h-4 w-4 ${reportType === 'compliance' ? 'text-red-400' : 'text-zinc-400'}`} />
                           <p className={`font-bold text-xs ${reportType === 'compliance' ? 'text-red-100' : 'text-zinc-300'}`}>Certificate</p>
                        </div>
                    </div>

                    <div 
                      onClick={() => setReportType("audit")}
                      className={`p-3 rounded-lg border cursor-pointer transition-all ${
                        reportType === "audit" 
                          ? "border-blue-500 bg-blue-500/10" 
                          : "border-zinc-700 bg-zinc-800/50 hover:bg-zinc-800"
                      }`}
                    >
                        <div className="flex items-center gap-2 mb-1">
                           <History className={`h-4 w-4 ${reportType === 'audit' ? 'text-blue-400' : 'text-zinc-400'}`} />
                           <p className={`font-bold text-xs ${reportType === 'audit' ? 'text-blue-100' : 'text-zinc-300'}`}>Audit Log</p>
                        </div>
                    </div>
                 </div>
              </div>

              <div className="space-y-2">
                <label className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest">3. Period</label>
                <div className="grid grid-cols-2 gap-3">
                   <div className="relative">
                      <Calendar className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-zinc-500" />
                      <Input type="date" className="bg-zinc-800 border-zinc-700 text-white h-9 text-xs pl-8" />
                   </div>
                   <div className="relative">
                      <Calendar className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-zinc-500" />
                      <Input type="date" className="bg-zinc-800 border-zinc-700 text-white h-9 text-xs pl-8" />
                   </div>
                </div>
              </div>

              <Button 
                className="w-full bg-red-600 hover:bg-red-700 mt-2 h-10 text-sm font-semibold shadow-lg shadow-red-900/20"
                onClick={handleGenerateReport}
                disabled={generating || !selectedLoanId}
              >
                {generating ? (
                  <><Loader2 className="mr-2 h-4 w-4 animate-spin" /> Generating Report...</>
                ) : (
                  <><Download className="mr-2 h-4 w-4" /> Download PDF</>
                )}
              </Button>
            </CardContent>
          </Card>

          {/* RECENT DOWNLOADS */}
          <Card>
            <CardHeader className="pb-3 border-b border-zinc-100">
              <CardTitle className="text-sm font-semibold">Recent Downloads</CardTitle>
            </CardHeader>
            <CardContent className="p-0">
                {[1, 2].map((i) => (
                    <div key={i} className="flex items-center justify-between p-3 hover:bg-zinc-50 transition-all border-b border-zinc-50 last:border-0 cursor-pointer group">
                        <div className="flex items-center gap-3">
                            <div className="h-8 w-8 bg-zinc-100 rounded flex items-center justify-center">
                                <FileText className="h-4 w-4 text-zinc-400 group-hover:text-red-600 transition-colors" />
                            </div>
                            <div>
                                <p className="text-xs font-medium text-zinc-900">Compliance_Q3_{i === 1 ? "Oceanic" : "Alpha"}.pdf</p>
                                <p className="text-[10px] text-zinc-500">Generated {i === 1 ? "2h" : "1d"} ago</p>
                            </div>
                        </div>
                        <Button variant="ghost" size="icon" className="h-7 w-7 text-zinc-300 hover:text-zinc-900">
                           <Download className="h-3.5 w-3.5" />
                        </Button>
                    </div>
                ))}
            </CardContent>
          </Card>
        </div>

        {/* RIGHT COLUMN: ENTERPRISE AUDIT LOG (TABLE VIEW) */}
        <div className="lg:col-span-2">
          <Card className="h-full border-zinc-200 shadow-sm flex flex-col">
            <CardHeader className="border-b border-zinc-100 bg-white pb-4">
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle className="flex items-center gap-2 text-lg">
                    <ShieldCheck className="h-5 w-5 text-zinc-900" /> System Audit Ledger
                  </CardTitle>
                  <CardDescription>Immutable record of all system events and user actions.</CardDescription>
                </div>
                <div className="flex gap-2">
                   <div className="relative">
                      <Search className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-zinc-400" />
                      <Input placeholder="Search logs..." className="h-9 w-48 pl-8 text-xs bg-zinc-50" />
                   </div>
                   <Button variant="outline" size="sm" className="h-9"><Filter className="h-3.5 w-3.5" /></Button>
                </div>
              </div>
            </CardHeader>
            <CardContent className="p-0 flex-1 overflow-hidden">
              {loading ? (
                 <div className="p-20 flex justify-center"><Loader2 className="h-8 w-8 animate-spin text-zinc-300" /></div>
              ) : (
                <div className="max-h-150 overflow-y-auto">
                  <Table>
                    <TableHeader className="bg-zinc-50/50 sticky top-0 z-10">
                      <TableRow>
                        <TableHead className="w-45">Timestamp</TableHead>
                        <TableHead>Event</TableHead>
                        <TableHead>User / System</TableHead>
                        <TableHead>IP Address</TableHead>
                        <TableHead className="text-right">Status</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {auditLogs.length === 0 ? (
                         <TableRow><TableCell colSpan={5} className="text-center py-10 text-zinc-400">No logs found.</TableCell></TableRow>
                      ) : (
                        auditLogs.map((log) => (
                          <TableRow key={log.id} className="group hover:bg-zinc-50/50">
                            <TableCell className="font-mono text-xs text-zinc-500">{new Date().toISOString().split('T')[0]} <span className="text-zinc-300">|</span> {log.timestamp}</TableCell>
                            <TableCell>
                                <div className="flex flex-col">
                                   <span className="font-medium text-zinc-900 text-sm">{log.type === 'critical' ? 'Risk Alert Triggered' : 'System Notification'}</span>
                                   <span className="text-xs text-zinc-500 truncate max-w-50" title={log.message}>{log.message}</span>
                                </div>
                            </TableCell>
                            <TableCell>
                               <div className="flex items-center gap-2">
                                  <div className="h-6 w-6 rounded-full bg-zinc-100 flex items-center justify-center">
                                     {log.type === 'critical' ? <AlertTriangle className="h-3 w-3 text-red-600" /> : <User className="h-3 w-3 text-zinc-500" />}
                                  </div>
                                  <span className="text-xs font-medium text-zinc-700">{log.type === 'critical' ? 'AI_Engine_v2' : 'Admin_User'}</span>
                               </div>
                            </TableCell>
                            <TableCell className="font-mono text-xs text-zinc-400">192.168.1.{Math.floor(Math.random() * 255)}</TableCell>
                            <TableCell className="text-right">
                               <Badge variant="outline" className="bg-green-50 text-green-700 border-green-200 text-[10px] uppercase font-bold">Logged</Badge>
                            </TableCell>
                          </TableRow>
                        ))
                      )}
                    </TableBody>
                  </Table>
                </div>
              )}
            </CardContent>
          </Card>
        </div>

      </div>
    </div>
  );
}