"use client";

import { useState, useEffect } from "react";
import { FileText, Download, ShieldCheck, History, User, Loader2, CheckCircle2, AlertTriangle, FileBarChart } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

// --- TYPES ---
interface Loan {
  id: number;
  borrower_name: string;
  risk_status: string;
}

interface Alert {
  id: number;
  message: string;
  type: "critical" | "warning";
  timestamp: string;
}

export default function ReportsPage() {
  const [loans, setLoans] = useState<Loan[]>([]);
  const [auditLogs, setAuditLogs] = useState<Alert[]>([]);
  const [loading, setLoading] = useState(true);
  
  // Generation State
  const [selectedLoanId, setSelectedLoanId] = useState<string>("");
  const [reportType, setReportType] = useState<"compliance" | "audit">("compliance");
  const [generating, setGenerating] = useState(false);

  // 1. FETCH REAL DATA
  useEffect(() => {
    const fetchData = async () => {
      try {
        // Fetch Loans for Dropdown
        const loansRes = await fetch("http://localhost:8000/api/loans");
        const loansData = await loansRes.json();
        setLoans(loansData);

        // Fetch Alerts for Audit Log
        const alertsRes = await fetch("http://localhost:8000/api/alerts");
        const alertsData = await alertsRes.json();
        setAuditLogs(alertsData);
      } catch (error) {
        console.error("Failed to load report data", error);
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, []);

  // 2. SIMULATE REPORT GENERATION & DOWNLOAD
  const handleGenerateReport = () => {
    if (!selectedLoanId) {
      alert("Please select a borrower first.");
      return;
    }

    setGenerating(true);
    const loan = loans.find(l => l.id.toString() === selectedLoanId);
    
    // Simulate server processing time
    setTimeout(() => {
      // Create a fake file
      const element = document.createElement("a");
      const fileContent = `
===================================================================
                     COMPLIANCE CERTIFICATE
===================================================================
BORROWER:       ${loan?.borrower_name}
DATE:           ${new Date().toLocaleDateString()}
REPORT ID:      ${Math.floor(Math.random() * 1000000)}
STATUS:         ${loan?.risk_status.toUpperCase()}

-------------------------------------------------------------------
1. FINANCIAL COVENANTS
   - Debt to EBITDA:      [CALCULATED] - SEE ATTACHMENT A
   - Interest Coverage:   [CALCULATED] - SEE ATTACHMENT A
   
2. CERTIFICATION
   We hereby certify that the above information is true and correct 
   derived from the unaudited financial statements.

3. DEFAULT STATUS
   ${loan?.risk_status === 'Healthy' ? 'No Default has occurred and is continuing.' : 'NOTICE: A Potential Event of Default has been detected.'}

-------------------------------------------------------------------
GENERATED BY COVENANT IQ SYSTEM | ${new Date().toISOString()}
===================================================================
      `;
      
      const file = new Blob([fileContent], {type: 'text/plain'});
      element.href = URL.createObjectURL(file);
      element.download = `${reportType === 'compliance' ? 'Compliance_Cert' : 'Audit_Log'}_${loan?.borrower_name.replace(/\s/g, '_')}.txt`;
      document.body.appendChild(element); 
      element.click();
      document.body.removeChild(element);
      
      setGenerating(false);
    }, 2000); // 2 second loading effect
  };

  return (
    <div className="space-y-8 max-w-7xl mx-auto pb-10">
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-zinc-900">Compliance & Reports</h1>
        <p className="text-zinc-500 mt-1">Generate regulatory reports and view immutable system audit logs.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
        
        {/* LEFT COLUMN: Report Generation */}
        <div className="md:col-span-1 space-y-6">
          <Card className="bg-zinc-900 text-white border-zinc-800 shadow-xl">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <FileText className="h-5 w-5 text-red-500" /> Generate Report
              </CardTitle>
              <CardDescription className="text-zinc-400">
                Create a consolidated compliance certificate for lenders or auditors.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-5">
              
              <div className="space-y-2">
                <label className="text-xs font-bold text-zinc-500 uppercase tracking-wider">Select Borrower</label>
                <Select onValueChange={setSelectedLoanId}>
                  <SelectTrigger className="w-full bg-zinc-800 border-zinc-700 text-white focus:ring-red-600">
                    <SelectValue placeholder={loading ? "Loading..." : "Select entity..."} />
                  </SelectTrigger>
                  <SelectContent className="bg-zinc-800 border-zinc-700 text-white">
                    {loans.map((loan) => (
                      <SelectItem key={loan.id} value={loan.id.toString()}>
                        {loan.borrower_name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-2">
                 <label className="text-xs font-bold text-zinc-500 uppercase tracking-wider">Report Type</label>
                 <div className="grid grid-cols-2 gap-3">
                    <div 
                      onClick={() => setReportType("compliance")}
                      className={`p-3 rounded-lg border cursor-pointer transition-all ${
                        reportType === "compliance" 
                          ? "border-red-500/50 bg-red-900/20" 
                          : "border-zinc-700 bg-zinc-800/50 hover:bg-zinc-800"
                      }`}
                    >
                        <div className="flex items-center gap-2 mb-1">
                           <FileBarChart className={`h-4 w-4 ${reportType === 'compliance' ? 'text-red-400' : 'text-zinc-400'}`} />
                           <p className={`font-bold text-sm ${reportType === 'compliance' ? 'text-red-100' : 'text-zinc-300'}`}>Certificate</p>
                        </div>
                        <p className="text-[10px] text-zinc-500">Standard LMA Format</p>
                    </div>

                    <div 
                      onClick={() => setReportType("audit")}
                      className={`p-3 rounded-lg border cursor-pointer transition-all ${
                        reportType === "audit" 
                          ? "border-blue-500/50 bg-blue-900/20" 
                          : "border-zinc-700 bg-zinc-800/50 hover:bg-zinc-800"
                      }`}
                    >
                        <div className="flex items-center gap-2 mb-1">
                           <History className={`h-4 w-4 ${reportType === 'audit' ? 'text-blue-400' : 'text-zinc-400'}`} />
                           <p className={`font-bold text-sm ${reportType === 'audit' ? 'text-blue-100' : 'text-zinc-300'}`}>Audit Log</p>
                        </div>
                        <p className="text-[10px] text-zinc-500">Full System History</p>
                    </div>
                 </div>
              </div>

              <Button 
                className="w-full bg-red-600 hover:bg-red-700 mt-4 h-12 text-base font-semibold"
                onClick={handleGenerateReport}
                disabled={generating || !selectedLoanId}
              >
                {generating ? (
                  <><Loader2 className="mr-2 h-5 w-5 animate-spin" /> Generating...</>
                ) : (
                  <><Download className="mr-2 h-5 w-5" /> Generate PDF</>
                )}
              </Button>
            </CardContent>
          </Card>

          {/* Recent Reports List */}
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-base font-semibold">Recently Generated</CardTitle>
            </CardHeader>
            <CardContent className="grid gap-1">
                {[1, 2].map((i) => (
                    <div key={i} className="flex items-center justify-between p-3 hover:bg-zinc-50 rounded-lg cursor-pointer group border border-transparent hover:border-zinc-100 transition-all">
                        <div className="flex items-center gap-3">
                            <div className="h-9 w-9 bg-zinc-100 rounded-md flex items-center justify-center">
                                <FileText className="h-5 w-5 text-zinc-400 group-hover:text-red-600 transition-colors" />
                            </div>
                            <div>
                                <p className="text-sm font-medium text-zinc-900">Compliance_Q3_{i === 1 ? "Oceanic" : "Alpha"}.pdf</p>
                                <p className="text-xs text-zinc-500">Generated {i === 1 ? "2 hours" : "1 day"} ago</p>
                            </div>
                        </div>
                        <Button variant="ghost" size="icon" className="h-8 w-8 text-zinc-300 hover:text-zinc-900">
                           <Download className="h-4 w-4" />
                        </Button>
                    </div>
                ))}
            </CardContent>
          </Card>
        </div>

        {/* RIGHT COLUMN: Audit Log */}
        <div className="md:col-span-2">
          <Card className="h-full border-zinc-200 shadow-sm flex flex-col">
            <CardHeader className="border-b border-zinc-100 bg-zinc-50/50">
              <div className="flex items-center justify-between">
                <CardTitle className="flex items-center gap-2">
                  <History className="h-5 w-5 text-zinc-500" /> System Audit Log
                </CardTitle>
                <Badge variant="outline" className="bg-white text-zinc-500 font-normal border-zinc-200">
                  <ShieldCheck className="h-3 w-3 mr-1 text-green-600" /> Blockchain Verified
                </Badge>
              </div>
            </CardHeader>
            <CardContent className="p-0 flex-1 overflow-hidden">
              {loading ? (
                 <div className="p-10 flex justify-center"><Loader2 className="h-8 w-8 animate-spin text-zinc-300" /></div>
              ) : (
                <div className="divide-y divide-zinc-100 max-h-150 overflow-y-auto">
                  {auditLogs.length === 0 ? (
                     <div className="p-8 text-center text-zinc-400">No recent system activity found.</div>
                  ) : (
                    auditLogs.map((log) => (
                      <div key={log.id} className="p-4 flex items-start gap-4 hover:bg-zinc-50/80 transition-colors">
                        <div className="mt-1 shrink-0">
                            {log.type === "critical" ? (
                                 <div className="h-8 w-8 rounded-full bg-red-100 flex items-center justify-center">
                                    <AlertTriangle className="h-4 w-4 text-red-600" />
                                 </div>
                            ) : (
                                 <div className="h-8 w-8 rounded-full bg-blue-100 flex items-center justify-center">
                                    <ShieldCheck className="h-4 w-4 text-blue-600" />
                                 </div>
                            )}
                        </div>
                        <div className="flex-1 min-w-0">
                          <div className="flex justify-between items-start">
                            <p className="font-semibold text-sm text-zinc-900 truncate pr-4">
                                {log.type === 'critical' ? 'Risk Alert Triggered' : 'System Notification'}
                            </p>
                            <span className="text-xs text-zinc-400 font-mono whitespace-nowrap">{log.timestamp}</span>
                          </div>
                          <p className="text-sm text-zinc-600 mt-0.5 leading-snug">{log.message}</p>
                          <div className="flex items-center gap-2 mt-2">
                            <span className="text-[10px] font-medium uppercase tracking-wider bg-zinc-100 px-2 py-0.5 rounded text-zinc-500 border border-zinc-200">
                               ID: LOG-{log.id}
                            </span>
                            <span className="text-[10px] text-zinc-400">
                               User: {log.type === 'critical' ? 'AI Risk Engine' : 'System Bot'}
                            </span>
                          </div>
                        </div>
                      </div>
                    ))
                  )}
                </div>
              )}
              <div className="p-3 border-t border-zinc-100 bg-zinc-50/30 text-center">
                 <Button variant="ghost" className="text-xs text-zinc-500 h-auto p-1 hover:bg-transparent hover:text-red-600 hover:underline">
                   View Full History (ReadOnly)
                 </Button>
              </div>
            </CardContent>
          </Card>
        </div>

      </div>
    </div>
  );
}